### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by marina-cyber** [ContrabassPlusPlus/time_series#10]
По сетям - R2 очень плохо.

Попробуйте хоть одну сеть прогнать с другими оптимизаторами, не Adam.

**Comment by ContrabassPlusPlus** [comment]
Здравствуйте! Я поменял оптимизатор, а также добавил эпох и увеличил размерность выходного вектора в рекуррентном слое, и после этого на GRU я получил r2 примерно 0.77.

**Comment by marina-cyber** [comment]
А было сколько? Улучшилось или ухудшилось? 

⁣Получить BlueMail для Android ​

На 21 янв. 2024 г., 01:29, в 01:29, ContrabassPlusPlus ***@***.***> написал:п>Здравствуйте! Я поменял оптимизатор, а также добавил эпох и увеличил

**Comment by ContrabassPlusPlus** [comment]
Улучшилось - было примерно 0.4.

**Comment by marina-cyber** [comment]
Ну можно попробовать не менять количество эпох, а попробовать ещё другие оптимизаторы. 
Первый возможно на 0 по градиенту почти сразу выходил. Текущий - чуть медленнее, но тоже плохо работает. 



⁣Получить BlueMail для Android ​

На 21 янв. 2024 г., 01:39, в 01:39, ContrabassPlusPlus ***@***.***> написал:п>Улучшилось - было примерно 0.4.

**Comment by marina-cyber** [comment]
А график логлосса кстати постройте на трейн и тесте. Сразу будет видно, сколько нужно эпох 

⁣Получить BlueMail для Android ​

На 21 янв. 2024 г., 01:39, в 01:39, ContrabassPlusPlus ***@***.***> написал:п>Улучшилось - было примерно 0.4.

**Comment by ContrabassPlusPlus** [comment]
Здравствуйте! Я смог получить r2 > 0.9 на GRU.

**Comment by marina-cyber** [comment]
проект зачтен.
